// Code generated by protoc-gen-go. DO NOT EDIT.
// source: engine.proto

package engine

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Side int32

const (
	Side_buy  Side = 0
	Side_sell Side = 1
)

var Side_name = map[int32]string{
	0: "buy",
	1: "sell",
}

var Side_value = map[string]int32{
	"buy":  0,
	"sell": 1,
}

func (x Side) String() string {
	return proto.EnumName(Side_name, int32(x))
}

func (Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{0}
}

type Order struct {
	Type                 Side     `protobuf:"varint,1,opt,name=Type,json=type,proto3,enum=Side" json:"Type,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,json=id,proto3" json:"ID,omitempty"`
	Amount               string   `protobuf:"bytes,3,opt,name=Amount,json=amount,proto3" json:"Amount,omitempty"`
	Price                string   `protobuf:"bytes,4,opt,name=Price,json=price,proto3" json:"Price,omitempty"`
	Pair                 string   `protobuf:"bytes,5,opt,name=Pair,json=pair,proto3" json:"Pair,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Order) Reset()         { *m = Order{} }
func (m *Order) String() string { return proto.CompactTextString(m) }
func (*Order) ProtoMessage()    {}
func (*Order) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{0}
}

func (m *Order) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Order.Unmarshal(m, b)
}
func (m *Order) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Order.Marshal(b, m, deterministic)
}
func (m *Order) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Order.Merge(m, src)
}
func (m *Order) XXX_Size() int {
	return xxx_messageInfo_Order.Size(m)
}
func (m *Order) XXX_DiscardUnknown() {
	xxx_messageInfo_Order.DiscardUnknown(m)
}

var xxx_messageInfo_Order proto.InternalMessageInfo

func (m *Order) GetType() Side {
	if m != nil {
		return m.Type
	}
	return Side_buy
}

func (m *Order) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Order) GetAmount() string {
	if m != nil {
		return m.Amount
	}
	return ""
}

func (m *Order) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Order) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

type OutputOrders struct {
	OrdersProcessed      string   `protobuf:"bytes,1,opt,name=OrdersProcessed,json=orders_processed,proto3" json:"OrdersProcessed,omitempty"`
	PartialOrder         string   `protobuf:"bytes,2,opt,name=PartialOrder,json=partial_order,proto3" json:"PartialOrder,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OutputOrders) Reset()         { *m = OutputOrders{} }
func (m *OutputOrders) String() string { return proto.CompactTextString(m) }
func (*OutputOrders) ProtoMessage()    {}
func (*OutputOrders) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{1}
}

func (m *OutputOrders) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OutputOrders.Unmarshal(m, b)
}
func (m *OutputOrders) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OutputOrders.Marshal(b, m, deterministic)
}
func (m *OutputOrders) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OutputOrders.Merge(m, src)
}
func (m *OutputOrders) XXX_Size() int {
	return xxx_messageInfo_OutputOrders.Size(m)
}
func (m *OutputOrders) XXX_DiscardUnknown() {
	xxx_messageInfo_OutputOrders.DiscardUnknown(m)
}

var xxx_messageInfo_OutputOrders proto.InternalMessageInfo

func (m *OutputOrders) GetOrdersProcessed() string {
	if m != nil {
		return m.OrdersProcessed
	}
	return ""
}

func (m *OutputOrders) GetPartialOrder() string {
	if m != nil {
		return m.PartialOrder
	}
	return ""
}

type BookInput struct {
	Pair                 string   `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookInput) Reset()         { *m = BookInput{} }
func (m *BookInput) String() string { return proto.CompactTextString(m) }
func (*BookInput) ProtoMessage()    {}
func (*BookInput) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{2}
}

func (m *BookInput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookInput.Unmarshal(m, b)
}
func (m *BookInput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookInput.Marshal(b, m, deterministic)
}
func (m *BookInput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookInput.Merge(m, src)
}
func (m *BookInput) XXX_Size() int {
	return xxx_messageInfo_BookInput.Size(m)
}
func (m *BookInput) XXX_DiscardUnknown() {
	xxx_messageInfo_BookInput.DiscardUnknown(m)
}

var xxx_messageInfo_BookInput proto.InternalMessageInfo

func (m *BookInput) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *BookInput) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

type BookArray struct {
	PriceAmount          []string `protobuf:"bytes,1,rep,name=price_amount,json=priceAmount,proto3" json:"price_amount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookArray) Reset()         { *m = BookArray{} }
func (m *BookArray) String() string { return proto.CompactTextString(m) }
func (*BookArray) ProtoMessage()    {}
func (*BookArray) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{3}
}

func (m *BookArray) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookArray.Unmarshal(m, b)
}
func (m *BookArray) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookArray.Marshal(b, m, deterministic)
}
func (m *BookArray) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookArray.Merge(m, src)
}
func (m *BookArray) XXX_Size() int {
	return xxx_messageInfo_BookArray.Size(m)
}
func (m *BookArray) XXX_DiscardUnknown() {
	xxx_messageInfo_BookArray.DiscardUnknown(m)
}

var xxx_messageInfo_BookArray proto.InternalMessageInfo

func (m *BookArray) GetPriceAmount() []string {
	if m != nil {
		return m.PriceAmount
	}
	return nil
}

type BookOutput struct {
	Buys                 []*BookArray `protobuf:"bytes,1,rep,name=Buys,json=buys,proto3" json:"Buys,omitempty"`
	Sells                []*BookArray `protobuf:"bytes,2,rep,name=Sells,json=sells,proto3" json:"Sells,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *BookOutput) Reset()         { *m = BookOutput{} }
func (m *BookOutput) String() string { return proto.CompactTextString(m) }
func (*BookOutput) ProtoMessage()    {}
func (*BookOutput) Descriptor() ([]byte, []int) {
	return fileDescriptor_770b178c3aab763f, []int{4}
}

func (m *BookOutput) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookOutput.Unmarshal(m, b)
}
func (m *BookOutput) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookOutput.Marshal(b, m, deterministic)
}
func (m *BookOutput) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookOutput.Merge(m, src)
}
func (m *BookOutput) XXX_Size() int {
	return xxx_messageInfo_BookOutput.Size(m)
}
func (m *BookOutput) XXX_DiscardUnknown() {
	xxx_messageInfo_BookOutput.DiscardUnknown(m)
}

var xxx_messageInfo_BookOutput proto.InternalMessageInfo

func (m *BookOutput) GetBuys() []*BookArray {
	if m != nil {
		return m.Buys
	}
	return nil
}

func (m *BookOutput) GetSells() []*BookArray {
	if m != nil {
		return m.Sells
	}
	return nil
}

func init() {
	proto.RegisterEnum("Side", Side_name, Side_value)
	proto.RegisterType((*Order)(nil), "Order")
	proto.RegisterType((*OutputOrders)(nil), "OutputOrders")
	proto.RegisterType((*BookInput)(nil), "BookInput")
	proto.RegisterType((*BookArray)(nil), "BookArray")
	proto.RegisterType((*BookOutput)(nil), "BookOutput")
}

func init() {
	proto.RegisterFile("engine.proto", fileDescriptor_770b178c3aab763f)
}

var fileDescriptor_770b178c3aab763f = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x52, 0x4d, 0x6f, 0xd4, 0x30,
	0x10, 0x25, 0x89, 0x93, 0x92, 0xd9, 0x6c, 0x59, 0x8d, 0x10, 0x72, 0x7b, 0x40, 0x21, 0x20, 0xb4,
	0x70, 0xc8, 0x61, 0x11, 0x3f, 0xa0, 0xe5, 0x43, 0xea, 0x01, 0x1a, 0xa5, 0x9c, 0x59, 0x79, 0x13,
	0x0b, 0xac, 0x66, 0x13, 0xcb, 0x71, 0x0e, 0xf9, 0x1b, 0xfc, 0x62, 0xe4, 0x71, 0x58, 0x84, 0x50,
	0x4f, 0xf1, 0x3c, 0xbf, 0x99, 0x79, 0xef, 0xc5, 0x90, 0xc9, 0xfe, 0x87, 0xea, 0x65, 0xa9, 0xcd,
	0x60, 0x87, 0xc2, 0x42, 0x7c, 0x6b, 0x5a, 0x69, 0xf0, 0x02, 0xd8, 0xb7, 0x59, 0x4b, 0x1e, 0xe4,
	0xc1, 0xf6, 0x7c, 0x17, 0x97, 0x77, 0xaa, 0x95, 0x35, 0xb3, 0xb3, 0x96, 0x78, 0x0e, 0xe1, 0xcd,
	0x47, 0x1e, 0xe6, 0xc1, 0x36, 0xad, 0x43, 0xd5, 0xe2, 0x33, 0x48, 0xae, 0x8e, 0xc3, 0xd4, 0x5b,
	0x1e, 0x11, 0x96, 0x08, 0xaa, 0xf0, 0x29, 0xc4, 0x95, 0x51, 0x8d, 0xe4, 0x8c, 0xe0, 0x58, 0xbb,
	0x02, 0x11, 0x58, 0x25, 0x94, 0xe1, 0x31, 0x81, 0x4c, 0x0b, 0x65, 0x8a, 0xef, 0x90, 0xdd, 0x4e,
	0x56, 0x4f, 0x96, 0x76, 0x8f, 0xf8, 0x06, 0x9e, 0xf8, 0x53, 0x65, 0x86, 0x46, 0x8e, 0xa3, 0x6c,
	0x49, 0x47, 0x5a, 0x6f, 0x06, 0x82, 0xf7, 0xfa, 0x0f, 0x8e, 0x2f, 0x21, 0xab, 0x84, 0xb1, 0x4a,
	0x74, 0xd4, 0xb1, 0xc8, 0x5a, 0x6b, 0x8f, 0xed, 0x89, 0x5f, 0xbc, 0x87, 0xf4, 0x7a, 0x18, 0xee,
	0x6f, 0x7a, 0x3d, 0x59, 0x27, 0xc0, 0x2d, 0x5d, 0x26, 0xd2, 0xd9, 0x49, 0xed, 0xd4, 0x51, 0x59,
	0x6a, 0x8f, 0x6a, 0x5f, 0x14, 0xa5, 0x6f, 0xbb, 0x32, 0x46, 0xcc, 0xf8, 0x02, 0x32, 0x32, 0xb0,
	0xf7, 0xee, 0x78, 0x90, 0x47, 0xdb, 0xb4, 0x5e, 0x11, 0xe6, 0xed, 0x17, 0x5f, 0x01, 0x1c, 0xdf,
	0x5b, 0xc1, 0xe7, 0xc0, 0xae, 0xa7, 0x79, 0x24, 0xe2, 0x6a, 0x07, 0xe5, 0x69, 0x54, 0xcd, 0x0e,
	0xd3, 0x3c, 0x62, 0x0e, 0xf1, 0x9d, 0xec, 0xba, 0x91, 0x87, 0xff, 0x11, 0xe2, 0xd1, 0x5d, 0xbc,
	0xbd, 0x00, 0xe6, 0x62, 0xc7, 0x33, 0x88, 0x0e, 0xd3, 0xbc, 0x79, 0x84, 0x8f, 0x81, 0xb9, 0x9b,
	0x4d, 0xb0, 0xfb, 0x15, 0x40, 0xf2, 0x89, 0x7e, 0x1c, 0xe6, 0x70, 0xb6, 0xc4, 0x84, 0x49, 0x49,
	0x21, 0x5c, 0xae, 0xcb, 0x7f, 0xe2, 0x7c, 0x0d, 0xeb, 0x85, 0xf1, 0x45, 0x98, 0x7b, 0x69, 0x1f,
	0xe2, 0x71, 0x48, 0x3e, 0x88, 0xbe, 0x91, 0xdd, 0x89, 0xb0, 0x7c, 0xf1, 0x15, 0xa4, 0x9f, 0xa5,
	0x6d, 0x7e, 0x3a, 0x89, 0xe8, 0x95, 0x52, 0x98, 0x97, 0xab, 0xf2, 0xaf, 0xe3, 0x43, 0x42, 0x6f,
	0xe8, 0xdd, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x8d, 0x39, 0x65, 0xfd, 0x53, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// EngineClient is the client API for Engine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type EngineClient interface {
	Process(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OutputOrders, error)
	ProcessMarket(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OutputOrders, error)
	Cancel(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error)
	FetchBook(ctx context.Context, in *BookInput, opts ...grpc.CallOption) (*BookOutput, error)
}

type engineClient struct {
	cc grpc.ClientConnInterface
}

func NewEngineClient(cc grpc.ClientConnInterface) EngineClient {
	return &engineClient{cc}
}

func (c *engineClient) Process(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OutputOrders, error) {
	out := new(OutputOrders)
	err := c.cc.Invoke(ctx, "/Engine/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) ProcessMarket(ctx context.Context, in *Order, opts ...grpc.CallOption) (*OutputOrders, error) {
	out := new(OutputOrders)
	err := c.cc.Invoke(ctx, "/Engine/ProcessMarket", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) Cancel(ctx context.Context, in *Order, opts ...grpc.CallOption) (*Order, error) {
	out := new(Order)
	err := c.cc.Invoke(ctx, "/Engine/Cancel", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *engineClient) FetchBook(ctx context.Context, in *BookInput, opts ...grpc.CallOption) (*BookOutput, error) {
	out := new(BookOutput)
	err := c.cc.Invoke(ctx, "/Engine/FetchBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EngineServer is the server API for Engine service.
type EngineServer interface {
	Process(context.Context, *Order) (*OutputOrders, error)
	ProcessMarket(context.Context, *Order) (*OutputOrders, error)
	Cancel(context.Context, *Order) (*Order, error)
	FetchBook(context.Context, *BookInput) (*BookOutput, error)
}

// UnimplementedEngineServer can be embedded to have forward compatible implementations.
type UnimplementedEngineServer struct {
}

func (*UnimplementedEngineServer) Process(ctx context.Context, req *Order) (*OutputOrders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (*UnimplementedEngineServer) ProcessMarket(ctx context.Context, req *Order) (*OutputOrders, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessMarket not implemented")
}
func (*UnimplementedEngineServer) Cancel(ctx context.Context, req *Order) (*Order, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Cancel not implemented")
}
func (*UnimplementedEngineServer) FetchBook(ctx context.Context, req *BookInput) (*BookOutput, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FetchBook not implemented")
}

func RegisterEngineServer(s *grpc.Server, srv EngineServer) {
	s.RegisterService(&_Engine_serviceDesc, srv)
}

func _Engine_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Engine/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Process(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_ProcessMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).ProcessMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Engine/ProcessMarket",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).ProcessMarket(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_Cancel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Order)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).Cancel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Engine/Cancel",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).Cancel(ctx, req.(*Order))
	}
	return interceptor(ctx, in, info, handler)
}

func _Engine_FetchBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BookInput)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EngineServer).FetchBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Engine/FetchBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EngineServer).FetchBook(ctx, req.(*BookInput))
	}
	return interceptor(ctx, in, info, handler)
}

var _Engine_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Engine",
	HandlerType: (*EngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _Engine_Process_Handler,
		},
		{
			MethodName: "ProcessMarket",
			Handler:    _Engine_ProcessMarket_Handler,
		},
		{
			MethodName: "Cancel",
			Handler:    _Engine_Cancel_Handler,
		},
		{
			MethodName: "FetchBook",
			Handler:    _Engine_FetchBook_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "engine.proto",
}
